

carsFamily = [
    {
      'id': 1,
      'manufacturer': 'Toyota',
      'model': 'Innova',
      'fuel': 'Diesel',
      'transmission': 'Manual',
      'seats': 8,
      'price': 3000,
    },
    {
      'id': 2,
      'manufacturer': 'Toyota',
      'model': 'Vios',
      'fuel': 'Diesel',
      'transmission': 'Manual',
      'seats': 5,
      'price': 2000,
    },
    {
      'id': 3,
      'manufacturer': 'Kia',
      'model': 'Soluto',
      'fuel' : 'Petrol',
      'transmission': 'Automatic',
      'seats': 5,
      'price': 2000,
    },
    {
      'id': 4,
      'manufacturer': 'Suzuki',
      'model': 'Dzire',
      'fuel': 'Petrol',
      'transmission': 'Manual',
      'seats': 5,
      'price': 2000,
    },
    {
      'id': 5,
      'manufacturer': 'Mitsubishi',
      'model': 'Mirage',
      'fuel': 'Petrol',
      'transmission': 'Automatic',
      'seats': 5,
      'price': 2000,
    },
    {
      'id': 6,
      'manufacturer': 'Toyota',
      'model': 'Avanza',
      'fuel': 'Diesel',
      'transmission': 'Manual',
      'seats': 7,
      'price': 3000,
    },
    {
      'id': 7,
      'manufacturer': 'Toyota',
      'model': 'Fortuner',
      'fuel': 'Petrol',
      'transmission': 'Automatic',
      'seats': 7,
      'price': 3500, 
    },
    {
      'id': 8,
      'manufacturer': 'Toyota',
      'model': 'Rush',
      'fuel': 'Petrol',
      'transmission': 'Automatic',
      'seats': 7,
      'price': 3000,
    },
    {
      'id': 9,
      'manufacturer': 'Toyota',
      'model': 'Land Cruiser',
      'fuel': 'Petrol',
      'transmission': 'Automatic',
      'seats': 8,
      'price': 15000,
    },
    {
      'id': 10,
      'manufacturer': 'Mg',
      'model': 'Five',
      'fuel': 'Petrol',
      'transmission': 'Automatic',
      'seats': 5,
      'price': 3200,
    }
]

carsVacation = [
  {
    'id': 1,
    'manufacturer': 'Toyota',
    'model': 'Hiace',
    'fuel': 'Diesel',
    'transmission': 'Manual',
    'seats': 14,
    'price': 4000,
  },
  {
    'id': 2,
    'manufacturer': 'Hyundai',
    'model': 'Starex',
    'fuel': 'Diesel',
    'transmission': 'Automatic',
    'seats': 10,
    'price': 4000,
  },
  {
    'id': 3,
    'manufacturer': 'Nissan',
    'model': 'Urvan',
    'fuel': 'Diesel',
    'transmission': 'Manual',
    'seats': 15,
    'price': 4000,
  },
  {
    'id': 4,
    'manufacturer': 'Mitsubishi',
    'model': 'L 300',
    'fuel': 'Diesel',
    'transmission': 'Manual',
    'seats': 17,
    'price': 3500,
  },
  {
    'id': 5,
    'manufacturer': 'Traditional',
    'model': 'Jeepney',
    'fuel': 'Diesel',
    'transmission': 'Manual',
    'seats': 23,
    'price': 3000,
  }
]

carsMover = [
  {
    'id': 1,
    'manufacturer': 'Mazda',
    'model': 'Bongo',
    'fuel': 'Diesel',
    'transmission': 'Manual',
    'capacity': 1000,
    'price': 3000,
  },
  {
    'id': 2,
    'manufacturer': 'Kia',
    'model': '2700',
    'fuel': 'Petrol',
    'transmission': 'Automatic',
    'capacity': 1300,
    'price': 3500,
  },
]